Change from using aescrypt to openssl

diff --git a/par-crypt b/par-crypt
--- a/par-crypt
+++ b/par-crypt
@@ -2,8 +2,8 @@
 # On input, it will tar the files, run `par2` on them to create a parchive,
 # tar all output files together, then encrypt the output.
 #
-# This requires [aescrypt][2] and [par2][1] to already be installed and callable
-# with those names.
+# This requires [par2][1] to already be installed and callable
+# with that name.
 #
 # Script should be called like the following:
 # ```
@@ -12,7 +12,6 @@
 #
 # Links:
 # [1]:https://github.com/Parchive/par2cmdline
-# [2]:https://www.aescrypt.com/linux_aes_crypt.html
 
 # If any command fails, just abort the whole switch
 set -e
@@ -25,6 +24,6 @@ if [[ $# -lt 3 ]]; then
 fi
 
 # Check for required commands
-command -v aescrypt >/dev/null 2>&1 || { echo "[ERROR] - aescrypt is required. Aborting." >&2; }
+command -v openssl >/dev/null 2>&1 || { echo "[ERROR] - openssl is required. Aborting." >&2; }
 command -v tar >/dev/null 2>&1 || { echo "[ERROR] - tar is required. Aborting." >&2; }
 command -v par2 >/dev/null 2>&1 || { echo "[ERROR] - par2 is required. Aborting." >&2; }
