Change command check to type
The type command works on alises as well.

diff --git a/par-crypt b/par-crypt
--- a/par-crypt
+++ b/par-crypt
@@ -25,6 +25,6 @@ if [[ $# -lt 3 ]]; then
 fi
 
 # Check for required commands
-command -v aescrypt >/dev/null 2>&1 || { echo "[ERROR] - aescrypt is required. Aborting." >&2; }
-command -v tar >/dev/null 2>&1 || { echo "[ERROR] - tar is required. Aborting." >&2; }
-command -v par2 >/dev/null 2>&1 || { echo "[ERROR] - par2 is required. Aborting." >&2; }
+type -p aescrypt >/dev/null 2>&1 || { echo "[ERROR] - aescrypt is required. Aborting." >&2; }
+type -p tar >/dev/null 2>&1 || { echo "[ERROR] - tar is required. Aborting." >&2; }
+type -p par2 >/dev/null 2>&1 || { echo "[ERROR] - par2 is required. Aborting." >&2; }
