Add checks on crypt script for commands, parameters

diff --git a/par-crypt b/par-crypt
--- a/par-crypt
+++ b/par-crypt
@@ -9,3 +9,16 @@
 # ```
 # par-crypt <password> <output-filename> <input-files...>
 # ```
+
+# If any command fails, just abort the whole switch
+set -e
+
+# Check we have the correct number of arguments
+if [[ $# -lt 4 ]]; then
+    echo "[ERROR] - Calling command should be $0 <password> <output-filename> <input-files...>";
+fi
+
+# Check for required commands
+command -v aescrypt >/dev/null 2>&1 || { echo "[ERROR] - aescrypt is required. Aborting." >&2; }
+command -v tar >/dev/null 2>&1 || { echo "[ERROR] - tar is required. Aborting." >&2; }
+command -v par2 >/dev/null 2>&1 || { echo "[ERROR] - par2 is required. Aborting." >&2; }
